### ISSUE TITLE
Visualizations

### ISSUE THREAD

**Issue by brett-szyjka** [buffalodevs/salary-survey#3]
Some visualizations would be nice, so people don't have to look through the data themselves

**Comment by brett-szyjka** [comment]
There may be more work to be done on data cleanup / normalization - all I really tried to do was classify role names into something that would be easily aggregate-able (sp?)

**Comment by BenKanouse** [comment]
I made a first attempt at the visualizations in this PR: https://github.com/buffalodevs/salary-survey/pull/4
